-- GAIN 2.0 trading ledger. PostgreSQL 15+.
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), firebase_uid text UNIQUE NOT NULL, member_id text UNIQUE, status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS exchange_accounts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), exchange text NOT NULL, credential_ref text NOT NULL, sandbox boolean NOT NULL DEFAULT true, permissions jsonb NOT NULL DEFAULT '{}', status text NOT NULL DEFAULT 'ACTIVE', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS bots (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), name text NOT NULL, exchange_account_id uuid REFERENCES exchange_accounts(id), symbol text NOT NULL, strategy_type text NOT NULL, status text NOT NULL, mode text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS bot_strategy_configs (bot_id uuid PRIMARY KEY REFERENCES bots(id), base_order_usd numeric(30,10) NOT NULL, take_profit_pct numeric(12,6) NOT NULL, trailing_tp_pct numeric(12,6), max_layers integer NOT NULL, step_deviation_pct numeric(12,6), step_scale numeric(12,6), volume_multiplier numeric(12,6), max_capital_usd numeric(30,10) NOT NULL, min_price numeric(30,10), max_price numeric(30,10), config jsonb NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS strategy_layers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), bot_id uuid NOT NULL REFERENCES bots(id), layer_no integer NOT NULL, layer_type text NOT NULL, trigger_price numeric(30,10), trigger_deviation_pct numeric(12,6), order_amount_usd numeric(30,10), order_quantity numeric(30,10), target_tp_price numeric(30,10), status text NOT NULL, filled_at timestamptz, UNIQUE(bot_id, layer_no));
CREATE TABLE IF NOT EXISTS orders (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), client_order_id text UNIQUE NOT NULL, idempotency_key text UNIQUE, bot_id uuid REFERENCES bots(id), user_id uuid NOT NULL REFERENCES users(id), exchange text NOT NULL, symbol text NOT NULL, side text NOT NULL, order_type text NOT NULL, requested_qty numeric(30,10), requested_price numeric(30,10), expected_notional numeric(30,10), status text NOT NULL, exchange_order_id text, rejection_reason text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS fills (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), order_id uuid NOT NULL REFERENCES orders(id), exchange_trade_id text, price numeric(30,10) NOT NULL, quantity numeric(30,10) NOT NULL, quote_amount numeric(30,10) NOT NULL, fee_amount numeric(30,10), fee_asset text, filled_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS positions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), bot_id uuid NOT NULL REFERENCES bots(id), symbol text NOT NULL, quantity numeric(30,10) NOT NULL DEFAULT 0, average_entry numeric(30,10) NOT NULL DEFAULT 0, realized_pnl numeric(30,10) NOT NULL DEFAULT 0, unrealized_pnl numeric(30,10) NOT NULL DEFAULT 0, total_fees numeric(30,10) NOT NULL DEFAULT 0, updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(bot_id, symbol));
CREATE TABLE IF NOT EXISTS risk_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, bot_id uuid, event_type text NOT NULL, severity text NOT NULL, metric text, value numeric(30,10), threshold numeric(30,10), action text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_orders_bot_status ON orders(bot_id,status);
CREATE INDEX IF NOT EXISTS idx_fills_order ON fills(order_id);
CREATE INDEX IF NOT EXISTS idx_risk_user_time ON risk_events(user_id,created_at DESC);
